server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /hema-crm/api/ {
        proxy_pass http://backend:8080/api/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/ {
        proxy_pass http://backend:8080/api/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location ^~ /hema-crm/assets/ {
        alias /usr/share/nginx/html/assets/;
        try_files $uri =404;
        add_header Cache-Control "no-cache";
    }

    location = /hema-crm/favicon.png {
        alias /usr/share/nginx/html/favicon.png;
        add_header Cache-Control "no-cache";
    }

    location = /hema-crm/FHSW_300x300px_black-300x297.png {
        alias /usr/share/nginx/html/FHSW_300x300px_black-300x297.png;
        add_header Cache-Control "no-cache";
    }

    location /hema-crm/ {
        rewrite ^/hema-crm/(.*)$ /$1 break;
        try_files $uri $uri/ /index.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
