"""Initial migration

Revision ID: 6daf726dd29d
Revises: 
Create Date: 2026-01-01 18:46:31.555654

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import table, column, Integer, String, Boolean

# revision identifiers, used by Alembic.
revision: str = '6daf726dd29d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkpoint',
                    sa.Column('date', sa.Date(), nullable=False),
                    sa.Column('balance', sa.Float(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()),
                    sa.Column('updated_at', sa.DateTime(), nullable=True, server_onupdate=sa.func.now()),
                    sa.PrimaryKeyConstraint('date')
                    )
    with op.batch_alter_table('checkpoint', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checkpoint_date'), ['date'], unique=False)

    op.create_table('contract',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=150), nullable=False),
                    sa.Column('description', sa.String(length=1000), nullable=True),
                    sa.Column('version', sa.String(length=250), nullable=True),
                    sa.Column('effective_from', sa.Date(), nullable=True),
                    sa.Column('effective_to', sa.Date(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()),
                    sa.Column('updated_at', sa.DateTime(), nullable=True, server_onupdate=sa.func.now()),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('title')
                    )
    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_id'), ['id'], unique=False)

    op.create_table('events',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=200), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('registration_start_date', sa.Date(), nullable=True),
                    sa.Column('event_date', sa.Date(), nullable=False),
                    sa.Column('start_time', sa.DateTime(), nullable=True),
                    sa.Column('end_time', sa.DateTime(), nullable=True),
                    sa.Column('location', sa.String(length=200), nullable=True),
                    sa.Column('max_participants', sa.Integer(), nullable=True),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('is_closed', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()),
                    sa.Column('updated_at', sa.DateTime(), nullable=True, server_onupdate=sa.func.now()),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_id'), ['id'], unique=False)

    op.create_table('member',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.String(length=100), nullable=False),
                    sa.Column('last_name', sa.String(length=100), nullable=False),
                    sa.Column('email', sa.String(length=320), nullable=False),
                    sa.Column('phone', sa.String(length=20), nullable=True),
                    sa.Column('date_of_birth', sa.Date(), nullable=True),
                    sa.Column('registration_date', sa.Date(), nullable=False),
                    sa.Column('is_deleted', sa.Boolean(), nullable=True),
                    sa.Column('notes', sa.String(length=3000), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()),
                    sa.Column('updated_at', sa.DateTime(), nullable=True, server_onupdate=sa.func.now()),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_member_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_member_id'), ['id'], unique=False)

    op.create_table('money_category',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()),
                    sa.Column('updated_at', sa.DateTime(), nullable=True, server_onupdate=sa.func.now()),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    with op.batch_alter_table('money_category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_money_category_id'), ['id'], unique=False)

    op.create_table('permission',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=250), nullable=False),
                    sa.Column('description', sa.String(length=1500), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()),
                    sa.Column('updated_at', sa.DateTime(), nullable=True, server_onupdate=sa.func.now()),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permission_id'), ['id'], unique=False)

    op.create_table('role',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=250), nullable=False),
                    sa.Column('description', sa.String(length=1500), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()),
                    sa.Column('updated_at', sa.DateTime(), nullable=True, server_onupdate=sa.func.now()),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_id'), ['id'], unique=False)

    op.create_table('season',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('start_date', sa.Date(), nullable=False),
                    sa.Column('end_date', sa.Date(), nullable=False),
                    sa.Column('is_finished', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()),
                    sa.Column('updated_at', sa.DateTime(), nullable=True, server_onupdate=sa.func.now()),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_season_id'), ['id'], unique=False)

    op.create_table('shelf',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('shelf_number', sa.String(length=250), nullable=False),
                    sa.Column('location', sa.String(length=200), nullable=True),
                    sa.Column('size', sa.String(length=250), nullable=True),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()),
                    sa.Column('updated_at', sa.DateTime(), nullable=True, server_onupdate=sa.func.now()),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('shelf_number')
                    )
    with op.batch_alter_table('shelf', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shelf_id'), ['id'], unique=False)

    op.create_table('shelf_plan',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('description', sa.String(length=2500), nullable=True),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('duration_days', sa.Integer(), nullable=False),
                    sa.Column('is_deleted', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()),
                    sa.Column('updated_at', sa.DateTime(), nullable=True, server_onupdate=sa.func.now()),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    with op.batch_alter_table('shelf_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shelf_plan_id'), ['id'], unique=False)

    op.create_table('training_form',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('description', sa.String(length=2500), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()),
                    sa.Column('updated_at', sa.DateTime(), nullable=True, server_onupdate=sa.func.now()),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    with op.batch_alter_table('training_form', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_form_id'), ['id'], unique=False)

    op.create_table('training_zone',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('size', sa.String(length=2500), nullable=False),
                    sa.Column('description', sa.String(length=3000), nullable=True),
                    sa.Column('is_available', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()),
                    sa.Column('updated_at', sa.DateTime(), nullable=True, server_onupdate=sa.func.now()),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('training_zone', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_zone_id'), ['id'], unique=False)

    op.create_table('event_training_zone_m2m',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('event_id', sa.Integer(), nullable=False),
                    sa.Column('training_zone_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()),
                    sa.Column('updated_at', sa.DateTime(), nullable=True, server_onupdate=sa.func.now()),
                    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
                    sa.ForeignKeyConstraint(['training_zone_id'], ['training_zone.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('event_training_zone_m2m', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_training_zone_m2m_id'), ['id'], unique=False)

    op.create_table('expense',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('category_id', sa.Integer(), nullable=False),
                    sa.Column('description', sa.Text, nullable=False),
                    sa.Column('amount', sa.Float(), nullable=False),
                    sa.Column('expense_date', sa.Date(), nullable=False),
                    sa.Column('is_recurring', sa.Boolean(), nullable=True),
                    sa.Column('status', sa.Enum('SCHEDULED', 'PAID', 'OVERDUE', 'CANCELLED', name='paymentstatus'),
                              nullable=True),
                    sa.Column('notes', sa.String(length=3000), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()),
                    sa.Column('updated_at', sa.DateTime(), nullable=True, server_onupdate=sa.func.now()),
                    sa.ForeignKeyConstraint(['category_id'], ['money_category.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_id'), ['id'], unique=False)

    op.create_table('instructor',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('member_id', sa.Integer(), nullable=False),
                    sa.Column('specialization', sa.String(length=200), nullable=False),
                    sa.Column('bio', sa.Text(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('hire_date', sa.DateTime(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()),
                    sa.Column('updated_at', sa.DateTime(), nullable=True, server_onupdate=sa.func.now()),
                    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('instructor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instructor_id'), ['id'], unique=False)

    op.create_table('member_contracts',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('member_id', sa.Integer(), nullable=False),
                    sa.Column('contract_id', sa.Integer(), nullable=False),
                    sa.Column('signed', sa.Boolean(), nullable=True),
                    sa.Column('signed_at', sa.DateTime(), nullable=True),
                    sa.Column('notes', sa.String(length=3000), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()),
                    sa.Column('updated_at', sa.DateTime(), nullable=True, server_onupdate=sa.func.now()),
                    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ),
                    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('member_id', 'contract_id', name='uq_member_contract')
                    )
    with op.batch_alter_table('member_contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_member_contracts_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_member_contracts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_member_contracts_member_id'), ['member_id'], unique=False)

    op.create_table('membership_plan',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('description', sa.String(length=2500), nullable=True),
                    sa.Column('membership_type', sa.Enum('MONTHLY', 'VISITS', name='membershiptype'), nullable=False),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('duration_days', sa.Integer(), nullable=True),
                    sa.Column('visit_count', sa.Integer(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(), nullable=True),
                    sa.Column('season_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()),
                    sa.Column('updated_at', sa.DateTime(), nullable=True, server_onupdate=sa.func.now()),
                    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    with op.batch_alter_table('membership_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_membership_plan_id'), ['id'], unique=False)

    op.create_table('payment',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('category_id', sa.Integer(), nullable=False),
                    sa.Column('description', sa.Text, nullable=False),
                    sa.Column('amount', sa.Float(), nullable=False),
                    sa.Column('payment_date', sa.Date(), nullable=False),
                    sa.Column('is_recurring', sa.Boolean(), nullable=True),
                    sa.Column('payment_method',
                              sa.Enum('TRANSFER', 'CASH', 'CARD', 'BLIK', 'BARTER', name='paymentmethod'),
                              nullable=True),
                    sa.Column('status', sa.Enum('SCHEDULED', 'PAID', 'OVERDUE', 'CANCELLED', name='paymentstatus'),
                              nullable=True),
                    sa.Column('notes', sa.String(length=3000), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()),
                    sa.Column('updated_at', sa.DateTime(), nullable=True, server_onupdate=sa.func.now()),
                    sa.ForeignKeyConstraint(['category_id'], ['money_category.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_id'), ['id'], unique=False)

    op.create_table('role_permission_m2m',
                    sa.Column('role_id', sa.Integer(), nullable=False),
                    sa.Column('permission_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('role_id', 'permission_id')
                    )
    op.create_table('schedule',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('training_form_id', sa.Integer(), nullable=False),
                    sa.Column('season_id', sa.Integer(), nullable=False),
                    sa.Column('day_of_week',
                              sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY',
                                      name='dayofweek'), nullable=False),
                    sa.Column('schedule_cycle', sa.Enum('WEEKLY', 'BI_WEEKLY', 'MONTHLY', name='schedulecycle'),
                              nullable=False),
                    sa.Column('start_time', sa.Time(), nullable=False),
                    sa.Column('end_time', sa.Time(), nullable=False),
                    sa.Column('max_participants', sa.Integer(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()),
                    sa.Column('updated_at', sa.DateTime(), nullable=True, server_onupdate=sa.func.now()),
                    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
                    sa.ForeignKeyConstraint(['training_form_id'], ['training_form.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_id'), ['id'], unique=False)

    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(length=250), nullable=False),
                    sa.Column('email', sa.String(length=250), nullable=False),
                    sa.Column('hashed_password', sa.String(length=1500), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('member_id', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()),
                    sa.Column('updated_at', sa.DateTime(), nullable=True, server_onupdate=sa.func.now()),
                    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('event_expenses',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('event_id', sa.Integer(), nullable=False),
                    sa.Column('expense_id', sa.Integer(), nullable=True),
                    sa.Column('description', sa.String(length=200), nullable=False),
                    sa.Column('amount', sa.Float(), nullable=False),
                    sa.Column('expense_date', sa.Date(), nullable=False),
                    sa.Column('notes', sa.String(length=3000), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()),
                    sa.Column('updated_at', sa.DateTime(), nullable=True, server_onupdate=sa.func.now()),
                    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
                    sa.ForeignKeyConstraint(['expense_id'], ['expense.id'], ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('event_expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_expenses_id'), ['id'], unique=False)

    op.create_table('event_registrations',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('event_id', sa.Integer(), nullable=False),
                    sa.Column('member_id', sa.Integer(), nullable=True),
                    sa.Column('payment_id', sa.Integer(), nullable=True),
                    sa.Column('registration_date', sa.DateTime(), nullable=True),
                    sa.Column('discount', sa.Float(), nullable=False),
                    sa.Column('notes', sa.String(length=3000), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()),
                    sa.Column('updated_at', sa.DateTime(), nullable=True, server_onupdate=sa.func.now()),
                    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
                    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
                    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('event_registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_registrations_id'), ['id'], unique=False)

    op.create_table('membership_payment_m2m',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('member_id', sa.Integer(), nullable=False),
                    sa.Column('plan_id', sa.Integer(), nullable=False),
                    sa.Column('payment_id', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()),
                    sa.Column('updated_at', sa.DateTime(), nullable=True, server_onupdate=sa.func.now()),
                    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
                    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ondelete='SET NULL'),
                    sa.ForeignKeyConstraint(['plan_id'], ['membership_plan.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('membership_payment_m2m', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_membership_payment_m2m_id'), ['id'], unique=False)

    op.create_table('schedule_instructor_m2m',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('schedule_id', sa.Integer(), nullable=False),
                    sa.Column('instructor_id', sa.Integer(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('notes', sa.String(length=200), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()),
                    sa.Column('updated_at', sa.DateTime(), nullable=True, server_onupdate=sa.func.now()),
                    sa.ForeignKeyConstraint(['instructor_id'], ['instructor.id'], ),
                    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('schedule_instructor_m2m', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_instructor_m2m_id'), ['id'], unique=False)

    op.create_table('schedule_training_zone_m2m',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('schedule_id', sa.Integer(), nullable=False),
                    sa.Column('training_zone_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()),
                    sa.Column('updated_at', sa.DateTime(), nullable=True, server_onupdate=sa.func.now()),
                    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
                    sa.ForeignKeyConstraint(['training_zone_id'], ['training_zone.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('schedule_training_zone_m2m', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_training_zone_m2m_id'), ['id'], unique=False)

    op.create_table('shelf_rental',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('shelf_id', sa.Integer(), nullable=False),
                    sa.Column('member_id', sa.Integer(), nullable=False),
                    sa.Column('plan_id', sa.Integer(), nullable=False),
                    sa.Column('payment_id', sa.Integer(), nullable=True),
                    sa.Column('contract_id', sa.Integer(), nullable=False),
                    sa.Column('start_date', sa.Date(), nullable=False),
                    sa.Column('end_date', sa.Date(), nullable=False),
                    sa.Column('notes', sa.Text(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()),
                    sa.Column('updated_at', sa.DateTime(), nullable=True, server_onupdate=sa.func.now()),
                    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ),
                    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
                    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ondelete='SET NULL'),
                    sa.ForeignKeyConstraint(['plan_id'], ['shelf_plan.id'], ),
                    sa.ForeignKeyConstraint(['shelf_id'], ['shelf.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('shelf_rental', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shelf_rental_id'), ['id'], unique=False)

    op.create_table('training_session',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('schedule_id', sa.Integer(), nullable=True),
                    sa.Column('session_date', sa.Date(), nullable=False),
                    sa.Column('notes', sa.String(length=3000), nullable=True),
                    sa.Column('is_cancelled', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()),
                    sa.Column('updated_at', sa.DateTime(), nullable=True, server_onupdate=sa.func.now()),
                    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('training_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_session_id'), ['id'], unique=False)

    op.create_table('user_role_m2m',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('role_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('user_id', 'role_id')
                    )
    op.create_table('training_form_instructor_m2m',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('training_session_id', sa.Integer(), nullable=False),
                    sa.Column('instructor_id', sa.Integer(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('notes', sa.String(length=200), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()),
                    sa.Column('updated_at', sa.DateTime(), nullable=True, server_onupdate=sa.func.now()),
                    sa.ForeignKeyConstraint(['instructor_id'], ['instructor.id'], ),
                    sa.ForeignKeyConstraint(['training_session_id'], ['training_session.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('training_form_instructor_m2m', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_form_instructor_m2m_id'), ['id'], unique=False)

    op.create_table('training_session_attendance_m2m',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('session_id', sa.Integer(), nullable=False),
                    sa.Column('member_id', sa.Integer(), nullable=False),
                    sa.Column('attended', sa.Boolean(), nullable=True),
                    sa.Column('notes', sa.String(length=200), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()),
                    sa.Column('updated_at', sa.DateTime(), nullable=True, server_onupdate=sa.func.now()),
                    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
                    sa.ForeignKeyConstraint(['session_id'], ['training_session.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('training_session_attendance_m2m', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_session_attendance_m2m_id'), ['id'], unique=False)

    # ### end Alembic commands ###
    permission = table(
        "permission",
        column("id", Integer),
        column("name", String(250)),
        column("description", String(1500)),
    )
    role = table(
        "role",
        column("id", Integer),
        column("name", String(250)),
        column("description", String(1500)),
    )
    # Role-permission association table (many-to-many)
    role_permission_m2m = table(
        "role_permission_m2m",
        column("role_id", Integer),
        column("permission_id", Integer),
    )

    op.bulk_insert(
        role,
        [
            {"name": "admin", "description": "Ultimate Lord", },
            {
                "name": "finance",
                "description": "A member of Quartermaster with an access to financial operations",
            },
            {"name": "member", "description": "The usual member of the Quartermaster", },
            {
                "name": "instructor",
                "description": "A member with additional rights to edit training forms, sessions and more",
            },
        ],
    )

    op.bulk_insert(
        permission,
        [
            {"name": "read:finance", "description": "Finance & Analytics: read"},
            {"name": "edit:finance", "description": "Finance & Analytics: manage"},
            {"name": "read:session", "description": "Training, Session, Instructors: read"},
            {"name": "edit:session", "description": "Training, Session, Instructors: manage"},
            {"name": "read:auth", "description": "Users, roles and permissions: read"},
            {"name": "edit:auth", "description": "Users, roles and permissions: manage"},
            {"name": "read:member", "description": "Members and instructors: read"},
            {"name": "edit:member", "description": "Members and instructors: manage"},
            {"name": "read:document", "description": "Document: read"},
            {"name": "edit:document", "description": "Document: manage"},
            {"name": "read:shelf", "description": "Shelf: read"},
            {"name": "edit:shelf", "description": "Shelf: manage"},
            {"name": "read:event", "description": "Shelf: read"},
            {"name": "edit:event", "description": "Shelf: manage"},
        ],
    )

    op.bulk_insert(
        role_permission_m2m,
        [
            # Admin
            *[{"role_id": 1, "permission_id": i} for i in range(1, 15)],
            # Finance
            *[{"role_id": 2, "permission_id": i} for i in (1, 2, 7, 8, 9, 10, 11, 12)],
            # Member
            *[{"role_id": 3, "permission_id": i} for i in (7, 8)],
            # Instructor
            *[{"role_id": 4, "permission_id": i} for i in (3, 4, 7, 8)],
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_session_attendance_m2m', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_session_attendance_m2m_id'))

    op.drop_table('training_session_attendance_m2m')
    with op.batch_alter_table('training_form_instructor_m2m', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_form_instructor_m2m_id'))

    op.drop_table('training_form_instructor_m2m')
    op.drop_table('user_role_m2m')
    with op.batch_alter_table('training_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_session_id'))

    op.drop_table('training_session')
    with op.batch_alter_table('shelf_rental', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shelf_rental_id'))

    op.drop_table('shelf_rental')
    with op.batch_alter_table('schedule_training_zone_m2m', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_training_zone_m2m_id'))

    op.drop_table('schedule_training_zone_m2m')
    with op.batch_alter_table('schedule_instructor_m2m', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_instructor_m2m_id'))

    op.drop_table('schedule_instructor_m2m')
    with op.batch_alter_table('membership_payment_m2m', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_membership_payment_m2m_id'))

    op.drop_table('membership_payment_m2m')
    with op.batch_alter_table('event_registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_registrations_id'))

    op.drop_table('event_registrations')
    with op.batch_alter_table('event_expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_expenses_id'))

    op.drop_table('event_expenses')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_id'))

    op.drop_table('user')
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_id'))

    op.drop_table('schedule')
    op.drop_table('role_permission_m2m')
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_id'))

    op.drop_table('payment')
    with op.batch_alter_table('membership_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_membership_plan_id'))

    op.drop_table('membership_plan')
    with op.batch_alter_table('member_contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_contracts_member_id'))
        batch_op.drop_index(batch_op.f('ix_member_contracts_id'))
        batch_op.drop_index(batch_op.f('ix_member_contracts_contract_id'))

    op.drop_table('member_contracts')
    with op.batch_alter_table('instructor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instructor_id'))

    op.drop_table('instructor')
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_id'))

    op.drop_table('expense')
    with op.batch_alter_table('event_training_zone_m2m', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_training_zone_m2m_id'))

    op.drop_table('event_training_zone_m2m')
    with op.batch_alter_table('training_zone', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_zone_id'))

    op.drop_table('training_zone')
    with op.batch_alter_table('training_form', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_form_id'))

    op.drop_table('training_form')
    with op.batch_alter_table('shelf_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shelf_plan_id'))

    op.drop_table('shelf_plan')
    with op.batch_alter_table('shelf', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shelf_id'))

    op.drop_table('shelf')
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_season_id'))

    op.drop_table('season')
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_id'))

    op.drop_table('role')
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permission_id'))

    op.drop_table('permission')
    with op.batch_alter_table('money_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_money_category_id'))

    op.drop_table('money_category')
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_id'))
        batch_op.drop_index(batch_op.f('ix_member_email'))

    op.drop_table('member')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_id'))

    op.drop_table('events')
    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_id'))

    op.drop_table('contract')
    with op.batch_alter_table('checkpoint', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checkpoint_date'))

    op.drop_table('checkpoint')
    # ### end Alembic commands ###
