"""Add field description table

Revision ID: 8e4a7c2c1f6b
Revises: 6daf726dd29d
Create Date: 2026-03-30 13:10:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8e4a7c2c1f6b"
down_revision: Union[str, None] = "6daf726dd29d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

FIELD_DESCRIPTION_SEED_ROWS = [{'table_name': 'checkpoint',
  'column_name': 'date',
  'transcription': 'Data',
  'data_type': 'date',
  'allowed_values': None,
  'description': 'Data przeprowadzenia punktu kontrolnego finansów (checkpoint)'},
 {'table_name': 'checkpoint',
  'column_name': 'balance',
  'transcription': 'Saldo',
  'data_type': 'float',
  'allowed_values': None,
  'description': 'Saldo środków w punkcie kontrolnym (stan kasy/konta)'},
 {'table_name': 'checkpoint',
  'column_name': 'created_at',
  'transcription': 'Data utworzenia',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Czas automatycznego utworzenia wpisu punktu kontrolnego'},
 {'table_name': 'checkpoint',
  'column_name': 'updated_at',
  'transcription': 'Data aktualizacji',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Czas ostatniej modyfikacji danych w punkcie kontrolnym'},
 {'table_name': 'contract',
  'column_name': 'id',
  'transcription': 'Identyfikator',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Unikalny numer identyfikacyjny wzoru umowy'},
 {'table_name': 'contract',
  'column_name': 'title',
  'transcription': 'Tytuł',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Nazwa lub tytuł określający rodzaj umowy'},
 {'table_name': 'contract',
  'column_name': 'description',
  'transcription': 'Opis',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Szczegółowy opis warunków lub przeznaczenia danego wzoru umowy'},
 {'table_name': 'contract',
  'column_name': 'version',
  'transcription': 'Wersja',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Oznaczenie wersji wzoru umowy (np. v1.0, 2024/01)'},
 {'table_name': 'contract',
  'column_name': 'effective_from',
  'transcription': 'Obowiązuje od',
  'data_type': 'date',
  'allowed_values': None,
  'description': 'Data rozpoczęcia obowiązywania danej wersji wzoru umowy'},
 {'table_name': 'contract',
  'column_name': 'effective_to',
  'transcription': 'Obowiązuje do',
  'data_type': 'date',
  'allowed_values': None,
  'description': 'Data zakończenia obowiązywania danej wersji wzoru umowy'},
 {'table_name': 'contract',
  'column_name': 'created_at',
  'transcription': 'Data utworzenia',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Data dodania wzoru umowy do bazy danych'},
 {'table_name': 'contract',
  'column_name': 'updated_at',
  'transcription': 'Data aktualizacji',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Data ostatniej zmiany w definicji wzoru umowy'},
 {'table_name': 'event_expenses',
  'column_name': 'id',
  'transcription': 'Identyfikator',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Unikalny numer identyfikacyjny wydatku przypisanego do wydarzenia'},
 {'table_name': 'event_expenses',
  'column_name': 'event_id',
  'transcription': 'ID wydarzenia',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Powiązanie wydatku z konkretnym wydarzeniem z tabeli events'},
 {'table_name': 'event_expenses',
  'column_name': 'expense_id',
  'transcription': 'ID wydatku',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Powiązanie z ogólnym wpisem kosztowym w tabeli expense'},
 {'table_name': 'event_expenses',
  'column_name': 'description',
  'transcription': 'Opis',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Szczegółowy opis kosztu poniesionego w ramach wydarzenia'},
 {'table_name': 'event_expenses',
  'column_name': 'amount',
  'transcription': 'Kwota',
  'data_type': 'float',
  'allowed_values': None,
  'description': 'Kwota wydatku rozliczanego w ramach danego wydarzenia'},
 {'table_name': 'event_expenses',
  'column_name': 'expense_date',
  'transcription': 'Data wydatku',
  'data_type': 'date',
  'allowed_values': None,
  'description': 'Dzień, w którym wydatek na wydarzenie został faktycznie poniesiony'},
 {'table_name': 'event_expenses',
  'column_name': 'notes',
  'transcription': 'Uwagi',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Dodatkowe informacje lub wyjaśnienia dotyczące kosztu wydarzenia'},
 {'table_name': 'event_expenses',
  'column_name': 'created_at',
  'transcription': 'Data utworzenia',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Czas zarejestrowania wydatku wydarzenia w systemie'},
 {'table_name': 'event_expenses',
  'column_name': 'updated_at',
  'transcription': 'Data aktualizacji',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Czas ostatniej poprawki w rozliczeniu kosztu wydarzenia'},
 {'table_name': 'event_registrations',
  'column_name': 'id',
  'transcription': 'Identyfikator',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Unikalny numer wpisu rejestracji na wydarzenie'},
 {'table_name': 'event_registrations',
  'column_name': 'event_id',
  'transcription': 'ID wydarzenia',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'ID wydarzenia, na które zapisał się uczestnik'},
 {'table_name': 'event_registrations',
  'column_name': 'member_id',
  'transcription': 'ID członka',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'ID członka klubu, który dokonał zgłoszenia na wydarzenie'},
 {'table_name': 'event_registrations',
  'column_name': 'payment_id',
  'transcription': 'ID płatności',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Odnośnik do wpisu o dokonanej opłacie wpisowej na wydarzenie'},
 {'table_name': 'event_registrations',
  'column_name': 'registration_date',
  'transcription': 'Data rejestracji',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Moment dokonania zgłoszenia na wydarzenie przez uczestnika'},
 {'table_name': 'event_registrations',
  'column_name': 'discount',
  'transcription': 'Zniżka',
  'data_type': 'float',
  'allowed_values': None,
  'description': 'Kwota udzielonej zniżki na opłatę za udział w wydarzeniu'},
 {'table_name': 'event_registrations',
  'column_name': 'notes',
  'transcription': 'Uwagi',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Specyficzne prośby lub uwagi dotyczące uczestnictwa w wydarzeniu'},
 {'table_name': 'event_registrations',
  'column_name': 'created_at',
  'transcription': 'Data utworzenia',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Czas zapisu rejestracji w bazie danych'},
 {'table_name': 'event_registrations',
  'column_name': 'updated_at',
  'transcription': 'Data aktualizacji',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Czas ostatniej modyfikacji danych zgłoszenia uczestnika'},
 {'table_name': 'event_training_zone_m2m',
  'column_name': 'id',
  'transcription': 'Identyfikator',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Identyfikator powiązania wydarzenia z wyznaczoną strefą treningową'},
 {'table_name': 'event_training_zone_m2m',
  'column_name': 'event_id',
  'transcription': 'ID wydarzenia',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'ID wydarzenia korzystającego z danej strefy treningowej'},
 {'table_name': 'event_training_zone_m2m',
  'column_name': 'training_zone_id',
  'transcription': 'ID strefy treningowej',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'ID strefy w klubie, która jest zajęta przez wydarzenie'},
 {'table_name': 'event_training_zone_m2m',
  'column_name': 'created_at',
  'transcription': 'Data utworzenia',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Moment zarezerwowania strefy na potrzeby wydarzenia'},
 {'table_name': 'event_training_zone_m2m',
  'column_name': 'updated_at',
  'transcription': 'Data aktualizacji',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Ostatnia aktualizacja szczegółów rezerwacji strefy przez wydarzenie'},
 {'table_name': 'events',
  'column_name': 'id',
  'transcription': 'Identyfikator',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Unikalny numer identyfikacyjny wydarzenia (np. seminarium, turniej)'},
 {'table_name': 'events',
  'column_name': 'name',
  'transcription': 'Nazwa',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Oficjalna nazwa wydarzenia organizowanego przez klub'},
 {'table_name': 'events',
  'column_name': 'description',
  'transcription': 'Opis',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Szczegółowy program, cel lub opis charakteru wydarzenia'},
 {'table_name': 'events',
  'column_name': 'registration_start_date',
  'transcription': 'Start rejestracji',
  'data_type': 'date',
  'allowed_values': None,
  'description': 'Data, od której uczestnicy mogą zapisywać się na wydarzenie'},
 {'table_name': 'events',
  'column_name': 'event_date',
  'transcription': 'Data wydarzenia',
  'data_type': 'date',
  'allowed_values': None,
  'description': 'Główny termin rozpoczęcia wydarzenia'},
 {'table_name': 'events',
  'column_name': 'start_time',
  'transcription': 'Czas rozpoczęcia',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Dokładna godzina rozpoczęcia części głównej wydarzenia'},
 {'table_name': 'events',
  'column_name': 'end_time',
  'transcription': 'Czas zakończenia',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Dokładna godzina zakończenia lub planowanego trwania wydarzenia'},
 {'table_name': 'events',
  'column_name': 'location',
  'transcription': 'Lokalizacja',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Miejsce przeprowadzenia wydarzenia (adres lub nazwa sali)'},
 {'table_name': 'events',
  'column_name': 'max_participants',
  'transcription': 'Maksymalna liczba uczestników',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Limit miejsc dostępnych dla uczestników danego wydarzenia'},
 {'table_name': 'events',
  'column_name': 'price',
  'transcription': 'Cena',
  'data_type': 'float',
  'allowed_values': None,
  'description': 'Podstawowy koszt uczestnictwa w wydarzeniu'},
 {'table_name': 'events',
  'column_name': 'is_closed',
  'transcription': 'Zamknięte',
  'data_type': 'bool',
  'allowed_values': None,
  'description': 'Oznacza, czy lista uczestników została już zamknięta'},
 {'table_name': 'events',
  'column_name': 'created_at',
  'transcription': 'Data utworzenia',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Data wprowadzenia planowanego wydarzenia do grafiku klubu'},
 {'table_name': 'events',
  'column_name': 'updated_at',
  'transcription': 'Data aktualizacji',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Data ostatniej edycji szczegółów dotyczących wydarzenia'},
 {'table_name': 'expense',
  'column_name': 'id',
  'transcription': 'Identyfikator',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Unikalny numer porządkowy wydatku (kosztu) klubu'},
 {'table_name': 'expense',
  'column_name': 'category_id',
  'transcription': 'ID kategorii',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Przynależność wydatku do określonej kategorii finansowej'},
 {'table_name': 'expense',
  'column_name': 'description',
  'transcription': 'Opis',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Tytuł wydatku (np. czynsz za salę, zakup sprzętu)'},
 {'table_name': 'expense',
  'column_name': 'amount',
  'transcription': 'Kwota',
  'data_type': 'float',
  'allowed_values': None,
  'description': 'Całkowita kwota pieniężna wydana na określony cel'},
 {'table_name': 'expense',
  'column_name': 'expense_date',
  'transcription': 'Data wydatku',
  'data_type': 'date',
  'allowed_values': None,
  'description': 'Dzień poniesienia kosztu przez klub'},
 {'table_name': 'expense',
  'column_name': 'is_recurring',
  'transcription': 'Cykliczne',
  'data_type': 'bool',
  'allowed_values': None,
  'description': 'Określa, czy jest to koszt powtarzający się co miesiąc/okres'},
 {'table_name': 'expense',
  'column_name': 'status',
  'transcription': 'Status',
  'data_type': 'PaymentStatus',
  'allowed_values': '["scheduled", "paid", "overdue", "cancelled"]',
  'description': 'Bieżący stan realizacji płatności za wydatek (np. opłacone)'},
 {'table_name': 'expense',
  'column_name': 'notes',
  'transcription': 'Uwagi',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Dowolne notatki administracyjne dotyczące danego wydatku'},
 {'table_name': 'expense',
  'column_name': 'created_at',
  'transcription': 'Data utworzenia',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Systemowy czas zarejestrowania wpisu o wydatku'},
 {'table_name': 'expense',
  'column_name': 'updated_at',
  'transcription': 'Data aktualizacji',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Systemowy czas ostatniej modyfikacji parametrów wydatku'},
 {'table_name': 'field_description',
  'column_name': 'id',
  'transcription': 'Identyfikator',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Unikalny numer rekordu słownika opisów pól bazy danych'},
 {'table_name': 'field_description',
  'column_name': 'table_name',
  'transcription': 'Nazwa tabeli',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Nazwa fizycznej tabeli w bazie, której dotyczy ten opis'},
 {'table_name': 'field_description',
  'column_name': 'column_name',
  'transcription': 'Nazwa kolumny',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Nazwa kolumny w tabeli, której znaczenie jest tu definiowane'},
 {'table_name': 'field_description',
  'column_name': 'transcription',
  'transcription': 'Polska nazwa pola',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Przyjazna dla użytkownika, polska etykieta opisująca pole'},
 {'table_name': 'field_description',
  'column_name': 'data_type',
  'transcription': 'Typ danych',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Informacja o typie programistycznym przechowywanej wartości (np. int)'},
 {'table_name': 'field_description',
  'column_name': 'allowed_values',
  'transcription': 'Dopuszczalne wartości',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Lista lub opis dozwolonych wartości dla danego pola (enum)'},
 {'table_name': 'field_description',
  'column_name': 'description',
  'transcription': 'Opis',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Dokładny komentarz objaśniający rolę biznesową danej kolumny'},
 {'table_name': 'field_description',
  'column_name': 'created_at',
  'transcription': 'Data utworzenia',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Data wprowadzenia opisu pola do słownika danych'},
 {'table_name': 'field_description',
  'column_name': 'updated_at',
  'transcription': 'Data aktualizacji',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Data ostatniej korekty tłumaczenia lub opisu pola'},
 {'table_name': 'instructor',
  'column_name': 'id',
  'transcription': 'Identyfikator',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Unikalny numer profilu instruktora w systemie'},
 {'table_name': 'instructor',
  'column_name': 'member_id',
  'transcription': 'ID członka',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'ID rekordu członka klubu, który posiada uprawnienia instruktorskie'},
 {'table_name': 'instructor',
  'column_name': 'specialization',
  'transcription': 'Specjalizacja',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Dziedzina fechtunku lub dziedzina, w której instruktor się specjalizuje'},
 {'table_name': 'instructor',
  'column_name': 'bio',
  'transcription': 'Biogram',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Krótki opis doświadczenia, osiągnięć lub profilu trenera'},
 {'table_name': 'instructor',
  'column_name': 'is_active',
  'transcription': 'Aktywne',
  'data_type': 'bool',
  'allowed_values': None,
  'description': 'Czy dany instruktor prowadzi obecnie zajęcia w klubie'},
 {'table_name': 'instructor',
  'column_name': 'hire_date',
  'transcription': 'Data zatrudnienia',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Moment rozpoczęcia oficjalnej współpracy trenerskiej z klubem'},
 {'table_name': 'instructor',
  'column_name': 'created_at',
  'transcription': 'Data utworzenia',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Czas zarejestrowania profilu instruktorskiego w bazie'},
 {'table_name': 'instructor',
  'column_name': 'updated_at',
  'transcription': 'Data aktualizacji',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Czas ostatniej edycji danych personalnych lub profesjonalnych instruktora'},
 {'table_name': 'member',
  'column_name': 'id',
  'transcription': 'Identyfikator',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Główny identyfikator (ID) klubowicza w systemie CRM'},
 {'table_name': 'member',
  'column_name': 'first_name',
  'transcription': 'Imię',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Imię członka klubu'},
 {'table_name': 'member',
  'column_name': 'last_name',
  'transcription': 'Nazwisko',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Nazwisko członka klubu'},
 {'table_name': 'member',
  'column_name': 'email',
  'transcription': 'Adres e-mail',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Adres e-mail wykorzystywany do kontaktu i logowania'},
 {'table_name': 'member',
  'column_name': 'phone',
  'transcription': 'Numer telefonu',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Numer telefonu kontaktowego członka klubu'},
 {'table_name': 'member',
  'column_name': 'date_of_birth',
  'transcription': 'Data urodzenia',
  'data_type': 'date',
  'allowed_values': None,
  'description': 'Data urodzenia klubowicza (używana m.in. do weryfikacji wieku)'},
 {'table_name': 'member',
  'column_name': 'registration_date',
  'transcription': 'Data rejestracji',
  'data_type': 'date',
  'allowed_values': None,
  'description': 'Pierwszy dzień, w którym osoba zapisała się do klubu'},
 {'table_name': 'member',
  'column_name': 'is_deleted',
  'transcription': 'Usunięte',
  'data_type': 'bool',
  'allowed_values': None,
  'description': 'Czy rekord członka jest oznaczony jako usunięty (soft delete)'},
 {'table_name': 'member',
  'column_name': 'notes',
  'transcription': 'Uwagi',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Ogólne uwagi administratora dotyczące danego członka'},
 {'table_name': 'member',
  'column_name': 'created_at',
  'transcription': 'Data utworzenia',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Dokładna data i czas wprowadzenia członka do systemu'},
 {'table_name': 'member',
  'column_name': 'updated_at',
  'transcription': 'Data aktualizacji',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Data i czas ostatniej zmiany w profilu członka'},
 {'table_name': 'member_contracts',
  'column_name': 'id',
  'transcription': 'Identyfikator',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Identyfikator faktu zawarcia umowy z członkiem klubu'},
 {'table_name': 'member_contracts',
  'column_name': 'member_id',
  'transcription': 'ID członka',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Referencja do klubowicza podpisującego daną umowę'},
 {'table_name': 'member_contracts',
  'column_name': 'contract_id',
  'transcription': 'ID umowy',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Referencja do konkretnego wzoru umowy w tabeli contract'},
 {'table_name': 'member_contracts',
  'column_name': 'signed',
  'transcription': 'Podpisane',
  'data_type': 'bool',
  'allowed_values': None,
  'description': 'Status potwierdzający, czy umowa została fizycznie podpisana'},
 {'table_name': 'member_contracts',
  'column_name': 'signed_at',
  'transcription': 'Data podpisania',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Moment, w którym złożono podpis pod umową'},
 {'table_name': 'member_contracts',
  'column_name': 'notes',
  'transcription': 'Uwagi',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Ewentualne notatki dotyczące odstępstw lub specyfiki umowy'},
 {'table_name': 'member_contracts',
  'column_name': 'created_at',
  'transcription': 'Data utworzenia',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Data przygotowania umowy dla członka klubu'},
 {'table_name': 'member_contracts',
  'column_name': 'updated_at',
  'transcription': 'Data aktualizacji',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Ostatnia zmiana stanu umowy lub powiązanych z nią notatek'},
 {'table_name': 'membership_payment_m2m',
  'column_name': 'id',
  'transcription': 'Identyfikator',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Unikalne powiązanie płatności z planem członkostwa uczestnika'},
 {'table_name': 'membership_payment_m2m',
  'column_name': 'member_id',
  'transcription': 'ID członka',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Członek, którego dotyczy płatność za abonament'},
 {'table_name': 'membership_payment_m2m',
  'column_name': 'plan_id',
  'transcription': 'ID planu',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Wykupiony przez członka plan członkostwa (membership_plan)'},
 {'table_name': 'membership_payment_m2m',
  'column_name': 'payment_id',
  'transcription': 'ID płatności',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'ID zapisu finansowego płatności za dane członkostwo'},
 {'table_name': 'membership_payment_m2m',
  'column_name': 'created_at',
  'transcription': 'Data utworzenia',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Moment zarejestrowania nowej płatności za członkostwo'},
 {'table_name': 'membership_payment_m2m',
  'column_name': 'updated_at',
  'transcription': 'Data aktualizacji',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Ostatnia zmiana w powiązaniu opłaty z konkretnym karnetem'},
 {'table_name': 'membership_plan',
  'column_name': 'id',
  'transcription': 'Identyfikator',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Unikalny identyfikator rodzaju karnetu lub planu członkostwa'},
 {'table_name': 'membership_plan',
  'column_name': 'name',
  'transcription': 'Nazwa rodzaju karnetu',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Nazwa planu (np. Open, 2 razy w tygodniu, Ulgowy)'},
 {'table_name': 'membership_plan',
  'column_name': 'description',
  'transcription': 'Opis',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Opis korzyści i zakresu danego typu karnetu'},
 {'table_name': 'membership_plan',
  'column_name': 'membership_type',
  'transcription': 'Typ członkostwa',
  'data_type': 'MembershipType',
  'allowed_values': '["monthly", "visits"]',
  'description': 'Określa, czy karnet jest czasowy (miesięczny) czy ilościowy (na wejścia)'},
 {'table_name': 'membership_plan',
  'column_name': 'price',
  'transcription': 'Cena',
  'data_type': 'float',
  'allowed_values': None,
  'description': 'Standardowa cena ryczałtowa za dany plan członkostwa'},
 {'table_name': 'membership_plan',
  'column_name': 'duration_days',
  'transcription': 'Liczba dni',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Liczba dni, przez które karnet pozostaje aktywny od daty zakupu'},
 {'table_name': 'membership_plan',
  'column_name': 'visit_count',
  'transcription': 'Liczba wejść',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Liczba treningów, w których uczestnik może wziąć udział (dla karnetów ilościowych)'},
 {'table_name': 'membership_plan',
  'column_name': 'is_deleted',
  'transcription': 'Usunięte',
  'data_type': 'bool',
  'allowed_values': None,
  'description': 'Oznaczenie karnetów, które nie są już dostępne w ofercie klubu'},
 {'table_name': 'membership_plan',
  'column_name': 'season_id',
  'transcription': 'ID sezonu',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Przynależność planu członkostwa do konkretnego sezonu treningowego'},
 {'table_name': 'membership_plan',
  'column_name': 'created_at',
  'transcription': 'Data utworzenia',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Moment utworzenia nowej definicji planu w systemie'},
 {'table_name': 'membership_plan',
  'column_name': 'updated_at',
  'transcription': 'Data aktualizacji',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Ostatnia korekta cen lub opisu danego planu członkostwa'},
 {'table_name': 'money_category',
  'column_name': 'id',
  'transcription': 'Identyfikator',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Unikalny numer kategorii finansowej (przychodu/kosztu)'},
 {'table_name': 'money_category',
  'column_name': 'name',
  'transcription': 'Nazwa',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Nazwa kategorii (np. Czynsze, Wyposażenie, Opłaty Członkowskie)'},
 {'table_name': 'money_category',
  'column_name': 'created_at',
  'transcription': 'Data utworzenia',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Systemowa data dodania nowej kategorii finansowej'},
 {'table_name': 'money_category',
  'column_name': 'updated_at',
  'transcription': 'Data aktualizacji',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Data ostatniej zmiany nazwy lub definicji kategorii pieniężnej'},
 {'table_name': 'payment',
  'column_name': 'id',
  'transcription': 'Identyfikator',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Unikalny identyfikator konkretnej transakcji finansowej (wpłaty/wypłaty)'},
 {'table_name': 'payment',
  'column_name': 'category_id',
  'transcription': 'ID kategorii',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Przynależność płatności do kategorii z tabeli money_category'},
 {'table_name': 'payment',
  'column_name': 'description',
  'transcription': 'Opis',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Krótki opis, za co dokładnie została dokonana ta konkretna wpłata'},
 {'table_name': 'payment',
  'column_name': 'amount',
  'transcription': 'Kwota',
  'data_type': 'float',
  'allowed_values': None,
  'description': 'Kwota pieniężna zarejestrowanej płatności'},
 {'table_name': 'payment',
  'column_name': 'payment_date',
  'transcription': 'Płatność data',
  'data_type': 'date',
  'allowed_values': None,
  'description': 'Data, pod którą księgowana jest wpłata w klubie'},
 {'table_name': 'payment',
  'column_name': 'is_recurring',
  'transcription': 'Cykliczne',
  'data_type': 'bool',
  'allowed_values': None,
  'description': 'Informacja, czy płatność jest częścią większej serii automatycznych rozliczeń'},
 {'table_name': 'payment',
  'column_name': 'payment_method',
  'transcription': 'Metoda płatności',
  'data_type': 'PaymentMethod',
  'allowed_values': '["transfer", "cash", "card", "blik", "barter"]',
  'description': 'Sposób dokonania zapłaty (np. BLIK, przelew, gotówka)'},
 {'table_name': 'payment',
  'column_name': 'status',
  'transcription': 'Status',
  'data_type': 'PaymentStatus',
  'allowed_values': '["scheduled", "paid", "overdue", "cancelled"]',
  'description': 'Aktualny stan płatności (zaplanowana, opłacona, zaległa)'},
 {'table_name': 'payment',
  'column_name': 'notes',
  'transcription': 'Uwagi',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Dowolne dodatkowe informacje o danej transakcji'},
 {'table_name': 'payment',
  'column_name': 'created_at',
  'transcription': 'Data utworzenia',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Data wprowadzenia rekordu płatności do bazy'},
 {'table_name': 'payment',
  'column_name': 'updated_at',
  'transcription': 'Data aktualizacji',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Data ostatniej aktualizacji informacji finansowej o transakcji'},
 {'table_name': 'permission',
  'column_name': 'id',
  'transcription': 'Identyfikator',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Unikalny numer identyfikacyjny uprawnienia systemowego'},
 {'table_name': 'permission',
  'column_name': 'name',
  'transcription': 'Nazwa',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Techniczna nazwa uprawnienia (np. view_members, edit_schedules)'},
 {'table_name': 'permission',
  'column_name': 'description',
  'transcription': 'Opis',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Szczegółowy opis tego, na co pozwala dane uprawnienie'},
 {'table_name': 'permission',
  'column_name': 'created_at',
  'transcription': 'Data utworzenia',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Data zdefiniowania uprawnienia w systemie'},
 {'table_name': 'permission',
  'column_name': 'updated_at',
  'transcription': 'Data aktualizacji',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Ostatnia zmiana w zakresie opisu uprawnienia'},
 {'table_name': 'role',
  'column_name': 'id',
  'transcription': 'Identyfikator',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Unikalny identyfikator roli użytkownika (np. Admin, Member)'},
 {'table_name': 'role',
  'column_name': 'name',
  'transcription': 'Nazwa',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Wyświetlana nazwa roli pełnionej przez osobę w CRM'},
 {'table_name': 'role',
  'column_name': 'description',
  'transcription': 'Opis',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Definicja odpowiedzialności i poziomu dostępu przypisanego do roli'},
 {'table_name': 'role',
  'column_name': 'created_at',
  'transcription': 'Data utworzenia',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Data utworzenia nowej roli systemowej'},
 {'table_name': 'role',
  'column_name': 'updated_at',
  'transcription': 'Data aktualizacji',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Ostatnia aktualizacja nazwy lub opisu uprawnień roli'},
 {'table_name': 'role_permission_m2m',
  'column_name': 'role_id',
  'transcription': 'ID roli',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Przypisanie konkretnej roli do zestawu uprawnień'},
 {'table_name': 'role_permission_m2m',
  'column_name': 'permission_id',
  'transcription': 'ID uprawnienia',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Uprawnienie przypisane do określonej roli w ramach tabeli łączącej'},
 {'table_name': 'schedule',
  'column_name': 'id',
  'transcription': 'Identyfikator',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Unikalny identyfikator pozycji w grafiku treningowym'},
 {'table_name': 'schedule',
  'column_name': 'training_form_id',
  'transcription': 'ID formy treningu',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Referencja do typu zajęć (np. rapier, miecz długi)'},
 {'table_name': 'schedule',
  'column_name': 'season_id',
  'transcription': 'ID sezonu',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Sezon, w którym dany grafik zajęć obowiązuje'},
 {'table_name': 'schedule',
  'column_name': 'day_of_week',
  'transcription': 'Dzień tygodnia',
  'data_type': 'DayOfWeek',
  'allowed_values': '["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", '
                    '"sunday"]',
  'description': 'Dzień tygodnia, w którym odbywają się cykliczne zajęcia'},
 {'table_name': 'schedule',
  'column_name': 'schedule_cycle',
  'transcription': 'Cykl grafiku',
  'data_type': 'ScheduleCycle',
  'allowed_values': '["weekly", "bi-weekly", "monthly"]',
  'description': 'Informacja o powtarzalności treningów (np. co tydzień)'},
 {'table_name': 'schedule',
  'column_name': 'start_time',
  'transcription': 'Czas rozpoczęcia',
  'data_type': 'time',
  'allowed_values': None,
  'description': 'Planowana godzina rozpoczęcia treningu'},
 {'table_name': 'schedule',
  'column_name': 'end_time',
  'transcription': 'Czas zakończenia',
  'data_type': 'time',
  'allowed_values': None,
  'description': 'Planowana godzina zakończenia treningu'},
 {'table_name': 'schedule',
  'column_name': 'max_participants',
  'transcription': 'Maksymalna liczba uczestników',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Limit osób mogących wziąć udział w tych konkretnych zajęciach'},
 {'table_name': 'schedule',
  'column_name': 'is_deleted',
  'transcription': 'Usunięte',
  'data_type': 'bool',
  'allowed_values': None,
  'description': 'Oznaczenie terminów treningów, które zostały trwale usunięte z grafiku'},
 {'table_name': 'schedule',
  'column_name': 'created_at',
  'transcription': 'Data utworzenia',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Data wprowadzenia punktu do grafiku klubowego'},
 {'table_name': 'schedule',
  'column_name': 'updated_at',
  'transcription': 'Data aktualizacji',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Data ostatniej zmiany godziny lub dnia w grafiku'},
 {'table_name': 'schedule_instructor_m2m',
  'column_name': 'id',
  'transcription': 'Identyfikator',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Unikalne powiązanie instruktora z konkretną pozycją w grafiku'},
 {'table_name': 'schedule_instructor_m2m',
  'column_name': 'schedule_id',
  'transcription': 'ID grafiku',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'ID zajęć z grafiku, które prowadzi dany instruktor'},
 {'table_name': 'schedule_instructor_m2m',
  'column_name': 'instructor_id',
  'transcription': 'ID instruktora',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'ID instruktora przypisanego do prowadzenia zajęć'},
 {'table_name': 'schedule_instructor_m2m',
  'column_name': 'is_active',
  'transcription': 'Aktywne',
  'data_type': 'bool',
  'allowed_values': None,
  'description': 'Czy dany instruktor jest aktualnie odpowiedzialny za te zajęcia'},
 {'table_name': 'schedule_instructor_m2m',
  'column_name': 'notes',
  'transcription': 'Uwagi',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Uwagi specyficzne dla danego przypisania trenera do zajęć'},
 {'table_name': 'schedule_instructor_m2m',
  'column_name': 'created_at',
  'transcription': 'Data utworzenia',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Data przypisania instruktora do stałego treningu w grafiku'},
 {'table_name': 'schedule_instructor_m2m',
  'column_name': 'updated_at',
  'transcription': 'Data aktualizacji',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Data ostatniej modyfikacji składu trenerskiego zajęć'},
 {'table_name': 'schedule_training_zone_m2m',
  'column_name': 'id',
  'transcription': 'Identyfikator',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Unikalne powiązanie terminu w grafiku z salą treningową'},
 {'table_name': 'schedule_training_zone_m2m',
  'column_name': 'schedule_id',
  'transcription': 'ID grafiku',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'ID terminu treningu, który odbywa się w danej strefie'},
 {'table_name': 'schedule_training_zone_m2m',
  'column_name': 'training_zone_id',
  'transcription': 'ID strefy treningowej',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'ID sali lub części klubu zajętej pod regularne zajęcia'},
 {'table_name': 'schedule_training_zone_m2m',
  'column_name': 'created_at',
  'transcription': 'Data utworzenia',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Data przypisania sali do cyklicznych treningów'},
 {'table_name': 'schedule_training_zone_m2m',
  'column_name': 'updated_at',
  'transcription': 'Data aktualizacji',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Data zmiany rezerwacji sali dla danego grafiku treningowego'},
 {'table_name': 'season',
  'column_name': 'id',
  'transcription': 'Identyfikator',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Unikalny numer identyfikacyjny sezonu klubowego (np. rok szkolny)'},
 {'table_name': 'season',
  'column_name': 'name',
  'transcription': 'Nazwa',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Przyjazna nazwa sezonu (np. Jesień-Zima 2024)'},
 {'table_name': 'season',
  'column_name': 'start_date',
  'transcription': 'Data rozpoczęcia',
  'data_type': 'date',
  'allowed_values': None,
  'description': 'Data oficjalnego otwarcia sezonu treningowego'},
 {'table_name': 'season',
  'column_name': 'end_date',
  'transcription': 'Data zakończenia',
  'data_type': 'date',
  'allowed_values': None,
  'description': 'Data planowanego zamknięcia danego sezonu w klubie'},
 {'table_name': 'season',
  'column_name': 'is_finished',
  'transcription': 'Zakończone',
  'data_type': 'bool',
  'allowed_values': None,
  'description': 'Flaga informująca, czy dany sezon został już historycznie zakończony'},
 {'table_name': 'season',
  'column_name': 'created_at',
  'transcription': 'Data utworzenia',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Data wprowadzenia sezonu do planów klubowych'},
 {'table_name': 'season',
  'column_name': 'updated_at',
  'transcription': 'Data aktualizacji',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Data ostatniej korekty ram czasowych sezonu'},
 {'table_name': 'shelf',
  'column_name': 'id',
  'transcription': 'Identyfikator',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Unikalny numer identyfikacyjny szafki lub półki klubowej'},
 {'table_name': 'shelf',
  'column_name': 'shelf_number',
  'transcription': 'Numer szafki',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Czytelny dla użytkownika numer lub symbol szafki (np. A12)'},
 {'table_name': 'shelf',
  'column_name': 'location',
  'transcription': 'Lokalizacja',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Opis miejsca w klubie, gdzie szafka się znajduje (np. Szatnia Męska)'},
 {'table_name': 'shelf',
  'column_name': 'size',
  'transcription': 'Rozmiar',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Parametr określający gabaryty szafki (mała, duża, pionowa)'},
 {'table_name': 'shelf',
  'column_name': 'description',
  'transcription': 'Opis',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Dowolne uwagi dotyczące przeznaczenia lub stanu szafki'},
 {'table_name': 'shelf',
  'column_name': 'is_deleted',
  'transcription': 'Usunięte',
  'data_type': 'bool',
  'allowed_values': None,
  'description': 'Oznacza szafki wycofane z użytkowania lub fizycznie usunięte'},
 {'table_name': 'shelf',
  'column_name': 'created_at',
  'transcription': 'Data utworzenia',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Data dodania nowej szafki do ewidencji klubowej'},
 {'table_name': 'shelf',
  'column_name': 'updated_at',
  'transcription': 'Data aktualizacji',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Ostatnia zmiana w parametrach technicznych szafki'},
 {'table_name': 'shelf_plan',
  'column_name': 'id',
  'transcription': 'Identyfikator',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Unikalny identyfikator cennika wynajmu szafek'},
 {'table_name': 'shelf_plan',
  'column_name': 'name',
  'transcription': 'Nazwa',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Nazwa planu najmu (np. Abonament na sprzęt roczny)'},
 {'table_name': 'shelf_plan',
  'column_name': 'description',
  'transcription': 'Opis',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Dokładne warunki korzystania z planu wynajmu'},
 {'table_name': 'shelf_plan',
  'column_name': 'price',
  'transcription': 'Cena',
  'data_type': 'float',
  'allowed_values': None,
  'description': 'Standardowy koszt najmu szafki w ramach tego planu'},
 {'table_name': 'shelf_plan',
  'column_name': 'duration_days',
  'transcription': 'Liczba dni',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Okres aktywności usługi najmu wyrażony w dniach'},
 {'table_name': 'shelf_plan',
  'column_name': 'is_deleted',
  'transcription': 'Usunięte',
  'data_type': 'bool',
  'allowed_values': None,
  'description': 'Informacja o wycofaniu planu wynajmu z bieżącej oferty'},
 {'table_name': 'shelf_plan',
  'column_name': 'created_at',
  'transcription': 'Data utworzenia',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Data stworzenia definicji planu najmu szafek'},
 {'table_name': 'shelf_plan',
  'column_name': 'updated_at',
  'transcription': 'Data aktualizacji',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Ostatnia modyfikacja kosztu lub czasu trwania najmu'},
 {'table_name': 'shelf_rental',
  'column_name': 'id',
  'transcription': 'Identyfikator',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Unikalny numer konkretnego aktu wynajęcia szafki'},
 {'table_name': 'shelf_rental',
  'column_name': 'shelf_id',
  'transcription': 'ID szafki',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Referencja do wynajętej szafki (tabela shelf)'},
 {'table_name': 'shelf_rental',
  'column_name': 'member_id',
  'transcription': 'ID członka',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'ID klubowicza, który wynajmuje szafkę na swój sprzęt'},
 {'table_name': 'shelf_rental',
  'column_name': 'plan_id',
  'transcription': 'ID planu',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Plan najmu, według którego rozliczany jest uczestnik'},
 {'table_name': 'shelf_rental',
  'column_name': 'payment_id',
  'transcription': 'ID płatności',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Referencja do transakcji opłacającej bieżący wynajem szafki'},
 {'table_name': 'shelf_rental',
  'column_name': 'contract_id',
  'transcription': 'ID umowy',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Umowa na najem sprzętu (jeśli klub wymaga oddzielnej formy)'},
 {'table_name': 'shelf_rental',
  'column_name': 'start_date',
  'transcription': 'Data rozpoczęcia',
  'data_type': 'date',
  'allowed_values': None,
  'description': 'Data przekazania szafki do użytkowania uczestnikowi'},
 {'table_name': 'shelf_rental',
  'column_name': 'end_date',
  'transcription': 'Data zakończenia',
  'data_type': 'date',
  'allowed_values': None,
  'description': 'Data planowanego zwolnienia szafki lub wygaśnięcia okresu najmu'},
 {'table_name': 'shelf_rental',
  'column_name': 'notes',
  'transcription': 'Uwagi',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Szczególne informacje dotyczące przedmiotu najmu lub kluczy'},
 {'table_name': 'shelf_rental',
  'column_name': 'created_at',
  'transcription': 'Data utworzenia',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Moment dokonania wpisu o nowym najmie w CRM'},
 {'table_name': 'shelf_rental',
  'column_name': 'updated_at',
  'transcription': 'Data aktualizacji',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Data ostatniego przedłużenia najmu lub zmiany przypisania płatności'},
 {'table_name': 'training_form',
  'column_name': 'id',
  'transcription': 'Identyfikator',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Unikalny identyfikator rodzaju uprawianej dyscypliny lub formy walki'},
 {'table_name': 'training_form',
  'column_name': 'name',
  'transcription': 'Nazwa',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Nazwa techniczna zajęć (np. Szabla polska, Zapasy historyczne)'},
 {'table_name': 'training_form',
  'column_name': 'description',
  'transcription': 'Opis',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Charakterystyka techniczna i merytoryczna danej formy treningu'},
 {'table_name': 'training_form',
  'column_name': 'created_at',
  'transcription': 'Data utworzenia',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Moment dodania nowej formy treningowej do oferty klubu'},
 {'table_name': 'training_form',
  'column_name': 'updated_at',
  'transcription': 'Data aktualizacji',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Ostatnia korekta nazwy lub zakresu tematycznego zajęć'},
 {'table_name': 'training_form_instructor_m2m',
  'column_name': 'id',
  'transcription': 'Identyfikator',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Powiązanie kompetencyjne instruktora z formą treningową'},
 {'table_name': 'training_form_instructor_m2m',
  'column_name': 'training_session_id',
  'transcription': 'ID sesji treningowej',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Powiązanie sesji treningowej z tabelą instruktorów'},
 {'table_name': 'training_form_instructor_m2m',
  'column_name': 'instructor_id',
  'transcription': 'ID instruktora',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'ID instruktora wyznaczonego do prowadzenia zajęć'},
 {'table_name': 'training_form_instructor_m2m',
  'column_name': 'is_active',
  'transcription': 'Aktywne',
  'data_type': 'bool',
  'allowed_values': None,
  'description': 'Potwierdza, czy uprawnienia do prowadzenia danej formy są obecnie aktywne'},
 {'table_name': 'training_form_instructor_m2m',
  'column_name': 'notes',
  'transcription': 'Uwagi',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Notatki o poziomie zaawansowania lub statusie trenera w tej dziedzinie'},
 {'table_name': 'training_form_instructor_m2m',
  'column_name': 'created_at',
  'transcription': 'Data utworzenia',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Czas dodania certyfikacji lub uprawnień trenerskich do bazy'},
 {'table_name': 'training_form_instructor_m2m',
  'column_name': 'updated_at',
  'transcription': 'Data aktualizacji',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Data weryfikacji lub zmiany zakresu uprawnień trenera'},
 {'table_name': 'training_session',
  'column_name': 'id',
  'transcription': 'Identyfikator',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Unikalny numer porządkowy konkretnego odbywającego się treningu'},
 {'table_name': 'training_session',
  'column_name': 'schedule_id',
  'transcription': 'ID grafiku',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'ID pozycji w grafiku (schedule), na podstawie której wygenerowano trening'},
 {'table_name': 'training_session',
  'column_name': 'session_date',
  'transcription': 'Data treningu',
  'data_type': 'date',
  'allowed_values': None,
  'description': 'Faktyczny dzień, w którym dany trening jest przeprowadzany'},
 {'table_name': 'training_session',
  'column_name': 'notes',
  'transcription': 'Uwagi',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Informacja o zrealizowanym temacie lekcji lub incydentach'},
 {'table_name': 'training_session',
  'column_name': 'is_cancelled',
  'transcription': 'Odwołane',
  'data_type': 'bool',
  'allowed_values': None,
  'description': 'Informacja, czy dany trening został odwołany w danym dniu'},
 {'table_name': 'training_session',
  'column_name': 'created_at',
  'transcription': 'Data utworzenia',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Systemowy czas zarejestrowania nowej sesji treningowej'},
 {'table_name': 'training_session',
  'column_name': 'updated_at',
  'transcription': 'Data aktualizacji',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Systemowy czas ostatniej modyfikacji informacji o sesji'},
 {'table_name': 'training_session_attendance_m2m',
  'column_name': 'id',
  'transcription': 'Identyfikator',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Numer wpisu na liście obecności dla konkretnego treningu'},
 {'table_name': 'training_session_attendance_m2m',
  'column_name': 'session_id',
  'transcription': 'ID sesji',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'ID treningu (training_session), na którym obecność była sprawdzana'},
 {'table_name': 'training_session_attendance_m2m',
  'column_name': 'member_id',
  'transcription': 'ID członka',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'ID klubowicza, którego obecność jest ewidencjonowana'},
 {'table_name': 'training_session_attendance_m2m',
  'column_name': 'attended',
  'transcription': 'Obecność',
  'data_type': 'bool',
  'allowed_values': None,
  'description': 'Informacja o faktycznym udziale członka w danych zajęciach'},
 {'table_name': 'training_session_attendance_m2m',
  'column_name': 'notes',
  'transcription': 'Uwagi',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Informacje o ewentualnym urazie lub szczególnych dokonaniach na lekcji'},
 {'table_name': 'training_session_attendance_m2m',
  'column_name': 'created_at',
  'transcription': 'Data utworzenia',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Moment wpisania klubowicza na listę obecności sesji'},
 {'table_name': 'training_session_attendance_m2m',
  'column_name': 'updated_at',
  'transcription': 'Data aktualizacji',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Data ostatniej zmiany statusu obecności dla sesji'},
 {'table_name': 'training_zone',
  'column_name': 'id',
  'transcription': 'Identyfikator',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Unikalny numer strefy (sali) treningowej w bazie danych'},
 {'table_name': 'training_zone',
  'column_name': 'name',
  'transcription': 'Nazwa',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Etykieta identyfikująca salę (np. Sala Szermiercza, Siłownia)'},
 {'table_name': 'training_zone',
  'column_name': 'size',
  'transcription': 'Rozmiar',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Pojemność lub wymiary danej powierzchni treningowej'},
 {'table_name': 'training_zone',
  'column_name': 'description',
  'transcription': 'Opis',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Informacje o nawierzchni lub wyposażeniu danej strefy'},
 {'table_name': 'training_zone',
  'column_name': 'is_available',
  'transcription': 'Dostępne',
  'data_type': 'bool',
  'allowed_values': None,
  'description': 'Czy strefa jest obecnie gotowa do prowadzenia treningów'},
 {'table_name': 'training_zone',
  'column_name': 'created_at',
  'transcription': 'Data utworzenia',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Moment zarejestrowania nowej sali/strefy w klubie'},
 {'table_name': 'training_zone',
  'column_name': 'updated_at',
  'transcription': 'Data aktualizacji',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Ostatnia korekta nazwy lub dostępności strefy'},
 {'table_name': 'user',
  'column_name': 'id',
  'transcription': 'Identyfikator',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Konto techniczne użytkownika w systemie Quartermaster'},
 {'table_name': 'user',
  'column_name': 'username',
  'transcription': 'Nazwa użytkownika',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Login sytemowy (username) używany przy uwierzytelnianiu'},
 {'table_name': 'user',
  'column_name': 'email',
  'transcription': 'Adres e-mail',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Kontaktowy adres e-mail powiązany z kontem użytkownika'},
 {'table_name': 'user',
  'column_name': 'hashed_password',
  'transcription': 'Hash hasła',
  'data_type': 'str',
  'allowed_values': None,
  'description': 'Bezpiecznie zakodowane (zahashowane) hasło dostępu'},
 {'table_name': 'user',
  'column_name': 'is_active',
  'transcription': 'Aktywne',
  'data_type': 'bool',
  'allowed_values': None,
  'description': 'Flaga decydująca o możliwości zalogowania się do panelu CRM'},
 {'table_name': 'user',
  'column_name': 'member_id',
  'transcription': 'ID członka',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Powiązanie konta użytkownika z fizyczną osobą (członkiem klubu)'},
 {'table_name': 'user',
  'column_name': 'created_at',
  'transcription': 'Data utworzenia',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Systemowy czas rejestracji nowego użytkownika'},
 {'table_name': 'user',
  'column_name': 'updated_at',
  'transcription': 'Data aktualizacji',
  'data_type': 'datetime',
  'allowed_values': None,
  'description': 'Data ostatniej zmiany hasła lub parametrów dostępowych użytkownika'},
 {'table_name': 'user_role_m2m',
  'column_name': 'user_id',
  'transcription': 'ID użytkownika',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Referencja do konta użytkownika, któremu nadawane są role'},
 {'table_name': 'user_role_m2m',
  'column_name': 'role_id',
  'transcription': 'ID roli',
  'data_type': 'int',
  'allowed_values': None,
  'description': 'Zestaw ról systemowych posiadanych przez określonego użytkownika'}]

POLISH_TABLE_NAME_MAP = {
    "checkpoint": "Punkt kontrolny",
    "contract": "Umowa",
    "event_expenses": "Wydatek wydarzenia",
    "event_registrations": "Rejestracja wydarzenia",
    "event_training_zone_m2m": "Powiązanie wydarzenia i strefy treningowej",
    "events": "Wydarzenie",
    "expense": "Wydatek",
    "field_description": "Opis pola",
    "instructor": "Instruktor",
    "member": "Członek",
    "member_contracts": "Umowa członka",
    "membership_payment_m2m": "Powiązanie członkostwa i płatności",
    "membership_plan": "Plan członkostwa",
    "money_category": "Kategoria finansowa",
    "payment": "Płatność",
    "permission": "Uprawnienie",
    "role": "Rola",
    "role_permission_m2m": "Powiązanie roli i uprawnienia",
    "schedule": "Grafik",
    "schedule_instructor_m2m": "Powiązanie grafiku i instruktora",
    "schedule_training_zone_m2m": "Powiązanie grafiku i strefy treningowej",
    "season": "Sezon",
    "shelf": "Szafka",
    "shelf_plan": "Plan szafki",
    "shelf_rental": "Wynajem szafki",
    "training_form": "Forma treningu",
    "training_form_instructor_m2m": "Powiązanie formy treningu i instruktora",
    "training_session": "Sesja treningowa",
    "training_session_attendance_m2m": "Obecność na sesji treningowej",
    "training_zone": "Strefa treningowa",
    "user": "Użytkownik",
    "user_role_m2m": "Powiązanie użytkownika i roli",
}

POLISH_ID_REFERENCE_MAP = {
    "category": "Kategoria",
    "contract": "Umowa",
    "event": "Wydarzenie",
    "expense": "Wydatek",
    "instructor": "Instruktor",
    "member": "Członek",
    "payment": "Płatność",
    "permission": "Uprawnienie",
    "plan": "Plan",
    "role": "Rola",
    "schedule": "Grafik",
    "season": "Sezon",
    "session": "Sesja",
    "shelf": "Szafka",
    "training_form": "Forma treningu",
    "training_session": "Sesja treningowa",
    "training_zone": "Strefa treningowa",
    "user": "Użytkownik",
}

for row in FIELD_DESCRIPTION_SEED_ROWS:
    column_name = row["column_name"]
    entity_name = None

    if column_name == "id":
        entity_name = POLISH_TABLE_NAME_MAP.get(row["table_name"])
    elif column_name.endswith("_id"):
        entity_name = POLISH_ID_REFERENCE_MAP.get(column_name[:-3])

    if entity_name:
        id_label = f"{entity_name} ID"
        row["transcription"] = id_label
        row["description"] = id_label


def upgrade() -> None:
    op.create_table(
        "field_description",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("table_name", sa.String(length=255), nullable=False),
        sa.Column("column_name", sa.String(length=255), nullable=False),
        sa.Column("transcription", sa.String(length=255), nullable=False),
        sa.Column("data_type", sa.String(length=255), nullable=False),
        sa.Column("allowed_values", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(), nullable=True, server_onupdate=sa.func.now()),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "table_name",
            "column_name",
            name="uq_field_description_table_name_column_name",
        ),
    )

    field_description_table = sa.table(
        "field_description",
        sa.column("table_name", sa.String(length=255)),
        sa.column("column_name", sa.String(length=255)),
        sa.column("transcription", sa.String(length=255)),
        sa.column("data_type", sa.String(length=255)),
        sa.column("allowed_values", sa.Text()),
        sa.column("description", sa.Text()),
    )
    op.bulk_insert(field_description_table, FIELD_DESCRIPTION_SEED_ROWS)

    with op.batch_alter_table("field_description", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_field_description_id"), ["id"], unique=False)


def downgrade() -> None:
    with op.batch_alter_table("field_description", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_field_description_id"))

    op.drop_table("field_description")
